name: CI Develop  
on:
  push:
    branches:
      - develop
env:
  BUCKET_NAME : "jesusgollonet.com"
  AWS_REGION : "us-east-1"
  DISTRIBUTION_ID: "E39IIH4TWRD4TD"
permissions:
  id-token: write
  contents: read
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      - uses: actions/cache@v4
        with:
          # note that the path includes the build directory
          path: |
            ~/.npm
            ${{ github.workspace }}/build/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - run: cd build && yarn install
      - run: ./bin/build 
