name: Deploy  
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME : "jesusgollonet.com"
  AWS_REGION : "us-east-1"
  DISTRIBUTION_ID: "E39IIH4TWRD4TD"
permissions:
  id-token: write
  contents: read
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: |
          echo ${{ steps.yarn-cache-dir-path.outputs.dir}}
          yarn cache dir 
          ls $(yarn cache dir)
      - run: cd build && yarn install
      - run: ./bin/build 
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: out 
          path: build/out/
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: out
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::450393336780:role/jgb-website-deploy-github-oidc
          role-session-name: github-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name: Sync files to S3  
        run: |
          aws s3 sync . s3://${{ env.BUCKET_NAME }}/
      - name: Clear cloudfront cache 
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths "/*" 

