# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS deploy workflow
on:
  push
env:
  BUCKET_NAME : "jesusgollonet.com"
  AWS_REGION : "us-east-1"
permissions:
  id-token: write
  contents: read
jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      - run: cd build && yarn install
      - run: ./bin/build 
      - name: test
        run: |
          echo "hello"
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::450393336780:role/jgb-website-deploy-github-oidc
          role-session-name: github-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy test file to s3
        run: |
          aws s3 cp ./README.md s3://${{ env.BUCKET_NAME }}/
